# openapi: "3.0.0"

# info:
#   title: "Useless sample api"
#   description: "A simple api that returns a 200 if you ping it."
#   version: "1.0"

# paths:
#   /ping:
#     get:
#       responses:
#         '200':
#           description: OK
#           content:
#             text/plain:
#               schema:
#                 type: string

entrypoint: gunicorn -b :$PORT app:app
env: flex
runtime: python

runtime_config:
    python_version: 3
